const express = require('express');
const router = express.Router();
const verifyToken = require('../middleware/verifyToken')
const taskContollers = require('../controllers/taskControllers')
const filterTask = require('../controllers/filterTask')
const allowedTo = require('../middleware/allowedTo')
const userRole = require('../utils/UeerRole')
router.route('/')
            .get(taskContollers.getAllTAsk)
            .post(verifyToken,allowedTo(userRole.USER),taskContollers.addTask)
router.route('/:taskid')
            .patch(verifyToken,allowedTo(userRole.USER),taskContollers.updateTask)
            .delete(verifyToken,allowedTo(userRole.USER),taskContollers.deleteTask)
router.route('/:title')
            .get(taskContollers.getTaskByTitle)
router.route('/:category')
            .get(taskContollers.getTaskbyCategory)
router.route('/:description')
            .get(taskContollers.getTaskByDescription)
router.route('/:filter')
            .get(filterTask.getFilterTask)
module.exports = router;